apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  name: worker
  namespace: kube-system
  annotations:
    cluster.k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
    cluster.k8s.io/cluster-api-autoscaler-node-group-max-size: "30"
spec:
  # do not specify replica count, as its going to be dynamically altered
  # for our custom scale up/down solution
  # replicas: 3
  selector:
    matchLabels:
      prow: worker
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        prow: worker
    spec:
      metadata:
        annotations:
          # Make rotation quick. Nothing but test jobs is supposed to be on these nodes
          kubermatic.io/skip-eviction: "true"
        labels:
          # Mark worker nodes, so we can schedule only specific jobs here using nodeSelector.
          kubermatic.io/worker: "true"
          isSpotInstance: "true"
      providerSpec:
        value:
          cloudProvider: aws
          cloudProviderSpec:
            accessKeyId: ""
            ami: ""
            assignPublicIP: true
            availabilityZone: eu-west-1b
            diskSize: 200
            diskType: gp3
            ebsVolumeEncrypted: false
            instanceProfile: kubernetes-__CLUSTER_ID__
            instanceType: t3.2xlarge
            region: eu-west-1
            secretAccessKey: ""
            isSpotInstance: true
            spotInstanceConfig:
              # to find the actual price, see console->EC2->Spot Requests->Pricing history
              maxPrice: "0.5"
            securityGroupIDs:
              - sg-065e347e7ce966cc9
            subnetId: subnet-0e7cd5468632ff41e
            tags:
              kubernetes.io/cluster/__CLUSTER_ID__: ""
              system/cluster: __CLUSTER_ID__
              system/project: __PROJECT_ID__
            vpcId: vpc-05b5e4db034fe2fa0
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: false
          sshPublicKeys:
            - __SSH_PUBKEY__
      versions:
        kubelet: 1.29.4
