prowjob_namespace: "prow"
pod_namespace: "default"
# log_level: debug

# If a repository contains open source code, consider adding it to
# plank.report_templates, plank.job_url_prefix_config and plank.default_decoration_config_entries
# to generate links to public-prow.kcp.k8c.io, which does not require
# authentication.

plank:
  pod_pending_timeout: 60m
  pod_unscheduled_timeout: 60m

  report_templates:
    "*": "[Full PR test history](https://prow.kcp.k8c.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}})"
    "kubestellar/kubestellar": "[Full PR test history](https://public-prow.kcp.k8c.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}})"

  job_url_prefix_config:
    "*": https://prow.kcp.k8c.io/view/
    "kubestellar/kubestellar": "https://public-prow.kcp.k8c.io/view/"

  default_decoration_config_entries:
    # default config
    - config:
        timeout: 2h
        grace_period: 5m
        utility_images:
          clonerefs: "gcr.io/k8s-prow/clonerefs:v20230518-c802d8aea4"
          initupload: "gcr.io/k8s-prow/initupload:v20230518-c802d8aea4"
          entrypoint: "gcr.io/k8s-prow/entrypoint:v20230518-c802d8aea4"
          sidecar: "gcr.io/k8s-prow/sidecar:v20230518-c802d8aea4"
        gcs_configuration:
          bucket: "s3://prow-data"
          path_strategy: "explicit"
        s3_credentials_secret: "s3-credentials-internal"
        ssh_key_secrets:
          - kubestellar-ci-bot-ssh-key
        ssh_host_fingerprints:
          - github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    - repo: "kubestellar/kubestellar"
      config:
        s3_credentials_secret: "s3-credentials-public"
        gcs_configuration:
          bucket: "s3://prow-public-data"

in_repo_config:
  enabled:
    "*": true

sinker:
  # How often sinker resyncs, defaults to 1h
  resync_period: 1m
  # How long build pods are kept after finishing, defaults to 24h
  max_pod_age: 2h
  # How long to keep ProwJob CRs, default is one week,
  # we increase it to 28 days and have a jobarchiver CronJob that
  # will move jobs older than 21d to another namespace.
  max_prowjob_age: 672h

deck:
  # repositories hidden in public-prow, but internal prow ignores this list and shows all repos
  hidden_repos: []
  rerun_auth_configs:
    "*":
      allow_anyone: true
  spyglass:
    # Configuring these will make an "Artifacts" link appear on the Spyglass page, linking
    # to gcsweb.
    gcs_browser_prefixes:
      '*': https://gcsweb.kcp.k8c.io/s3/
      'kubestellar/kubestellar': https://public-gcsweb.kcp.k8c.io/s3/
    # required so that public periodics can point to the correct gcsweb
    # otherwise, gcsweb-public will just redirect to Google Cloud Console
    # instead of showing artifacts
    gcs_browser_prefixes_by_bucket:
      '*': https://gcsweb.kcp.k8c.io/s3/
      'prow-data': https://gcsweb.kcp.k8c.io/s3/
      'prow-public-data': https://public-gcsweb.kcp.k8c.io/s3/
    lenses:
      - required_files:
          - started.json
        optional_files:
          - finished.json
        lens:
          name: metadata
      - required_files:
          - build-log.txt
        lens:
          name: buildlog
          config:
            highlight_regexes:
              - timed out
              - "ERROR"
              - (FAIL|Failure \[)\b
              - panic\b
              - ^E\d{4} \d\d:\d\d:\d\d\.\d\d\d]
              - unbound variable
              - no more retries left\.
              - ^Retry [0-9]+\/[0-9]+ exited [^0], retrying in [0-9]+ seconds
              - npm ERR!
              - "WARNING: DATA RACE"
      - required_files:
          - artifacts/junit.*\.xml
        lens:
          name: junit
    size_limit: 500000000 # 500MB

github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

tide:
  pr_status_base_urls:
    "*": https://prow.kcp.k8c.io/pr

  merge_method:
    kcp-dev: merge
    kubestellar: merge

  queries:
    # no release notes
    - repos:
        - kubestellar/kubestellar
      labels:
        - lgtm
        - approved
      missingLabels:
        - "dco-signoff: no"
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase

branch-protection:
  orgs:
    kcp-dev:
      repos:
        kcp:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"
        kcp-operator:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"
        api-syncagent:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"
        helm-charts:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
        infra:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
        multicluster-provider:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"
        kcp.io:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
        client-go:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"
            - "^kcp-.+$"
        code-generator:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"
            - "^kcp-.+$"
        apimachinery:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"
            - "^kcp-.+$"
        kubernetes:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^kcp-.+$"
        logicalcluster:
          protect: true
          required_status_checks:
            contexts:
              - dco
          restrictions:
            users: []
            teams:
              - kcp-dev/kcp-admins
          include:
            - "^main$"
            - "^release-.+$"

presets:
  ################################################################
  # Default preset, will be applied to all jobs

  - env:
      - name: DOCKER_REGISTRY_MIRROR_ADDR
        valueFrom:
          configMapKeyRef:
            name: cluster-config
            key: DOCKER_REGISTRY_MIRROR_ADDR
            optional: true
    volumeMounts:
      - name: scratch
        mountPath: /scratch
    volumes:
      - name: scratch
        emptyDir:
          medium: Memory

  ################################################################
  # opt-in to using the internal Athens go modules cache

  - labels:
      preset-goproxy: "true"
    env:
      - name: GOPROXY
        valueFrom:
          configMapKeyRef:
            name: cluster-config
            key: GOPROXY

  ################################################################
  # (prow-cluster only) mount the god kubeconfig

  - labels:
      preset-prow-kubeconfig: "true"
    volumeMounts:
      - name: prow-kubeconfig
        mountPath: /etc/prow/kubeconfig
    volumes:
      - name: prow-kubeconfig
        secret:
          secretName: kubeconfig

  ################################################################
  # (prow-cluster only) username and password for GHCR

  - labels:
      preset-ghcr-credentials: "true"
    env:
      - name: KCP_GHCR_USERNAME
        valueFrom:
          secretKeyRef:
            name: ghcr-credentials
            key: username
      - name: KCP_GHCR_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ghcr-credentials
            key: password
