apiVersion: v1
data:
  config.yaml: |
    prowjob_namespace: prow
    pod_namespace: test-pods

    in_repo_config:
      enabled:
        "*": true

    deck:
     spyglass:
       gcs_browser_prefix: 'https://s3.console.aws.amazon.com/s3/buckets/'
       lenses:
       - lens:
           name: metadata
         required_files:
           - ^(?:started|finished)\.json$
         optional_files:
           - ^(?:podinfo|prowjob)\.json$
       - lens:
           config:
           name: buildlog
         required_files:
         - build-log.txt
       - lens:
           name: junit
         required_files:
         - .*/junit.*\.xml
       - lens:
           name: podinfo
         required_files:
         - podinfo.json

    plank:
      job_url_prefix_config:
        "*": https://prow2.kubestellar.io/view/
      report_templates:
        '*': >-
            [Full PR test history](https://prow2.kubestellar.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
            [Your PR dashboard](https://prow2.kubestellar.io/pr?query=is:pr+state:open+author:{{with
            index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
      default_decoration_config_entries:
      - config:
          gcs_configuration:
            bucket: s3://prow-logs
            path_strategy: explicit
          github_api_endpoints:
            - http://ghproxy
            - https://api.github.com
          github_app_id: "1227751"
          github_app_private_key_secret:
            name: github-token
            key: cert
          s3_credentials_secret: s3-credentials
          utility_images:
            clonerefs: us-docker.pkg.dev/k8s-infra-prow/images/clonerefs:v20240802-66b115076
            entrypoint: us-docker.pkg.dev/k8s-infra-prow/images/entrypoint:v20240802-66b115076
            initupload: us-docker.pkg.dev/k8s-infra-prow/images/initupload:v20240802-66b115076
            sidecar: us-docker.pkg.dev/k8s-infra-prow/images/sidecar:v20240802-66b115076

    tide:
      queries:
      - labels:
        - lgtm
        - approved
        missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
        orgs:
        - kubestellar

    decorate_all_jobs: true
    periodics:
    - interval: 30m
      agent: kubernetes
      name: echo-test
      spec:
        containers:
        - image: alpine
          command: ["/bin/date"]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"prowjob_namespace: prow\npod_namespace: test-pods\n\nin_repo_config:\n  enabled:\n    \"*\": true\n\ndeck:\n spyglass:\n   gcs_browser_prefix: 'https://s3.console.aws.amazon.com/s3/buckets/'\n   lenses:\n   - lens:\n       name: metadata\n     required_files:\n       - ^(?:started|finished)\\.json$\n     optional_files:\n       - ^(?:podinfo|prowjob)\\.json$\n   - lens:\n       config:\n       name: buildlog\n     required_files:\n     - build-log.txt\n   - lens:\n       name: junit\n     required_files:\n     - .*/junit.*\\.xml\n   - lens:\n       name: podinfo\n     required_files:\n     - podinfo.json\n\nplank:\n  job_url_prefix_config:\n    \"*\": https://prow2.kubestellar.io/view/\n  report_templates:\n    '*': \u003e-\n        [Full PR test history](https://prow2.kubestellar.io/pr-history?org={{.Spec.Refs.Org}}\u0026repo={{.Spec.Refs.Repo}}\u0026pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).\n        [Your PR dashboard](https://prow2.kubestellar.io/pr?query=is:pr+state:open+author:{{with\n        index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).\n  default_decoration_config_entries:\n  - config:\n      gcs_configuration:\n        bucket: s3://prow-logs\n        path_strategy: explicit\n      github_api_endpoints:\n        - http://ghproxy\n        - https://api.github.com\n      github_app_id: \"1227751\"\n      github_app_private_key_secret:\n        name: github-token\n        key: cert\n      s3_credentials_secret: s3-credentials\n      utility_images:\n        clonerefs: us-docker.pkg.dev/k8s-infra-prow/images/clonerefs:v20240802-66b115076\n        entrypoint: us-docker.pkg.dev/k8s-infra-prow/images/entrypoint:v20240802-66b115076\n        initupload: us-docker.pkg.dev/k8s-infra-prow/images/initupload:v20240802-66b115076\n        sidecar: us-docker.pkg.dev/k8s-infra-prow/images/sidecar:v20240802-66b115076\n\ntide:\n  queries:\n  - labels:\n    - lgtm\n    - approved\n    missingLabels:\n    - needs-rebase\n    - do-not-merge/hold\n    - do-not-merge/work-in-progress\n    - do-not-merge/invalid-owners-file\n    orgs:\n    - kubestellar\n\ndecorate_all_jobs: true\nperiodics:\n- interval: 1m\n  agent: kubernetes\n  name: echo-test\n  spec:\n    containers:\n    - image: alpine\n      command: [\"/bin/date\"]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config","namespace":"prow"}}
  creationTimestamp: "2025-04-29T16:57:29Z"
  name: config
  namespace: prow
  resourceVersion: "7680453"
  uid: 2757c871-a973-4691-a846-420a5d1a312d
